#!/bin/bash
USERGROUP=$1
PKGNAME=$2
VERSION=$3
RELEASE=${4:-1}
sudo() {
    # yah, twisted.  sudo runs NOT as root!
    su nobody -s /bin/bash -c "$*"
}
echo building python $VERSION
cd /tmp

# run the build as nobody
sudo wget -q https://www.python.org/ftp/python/$VERSION/Python-$VERSION.tar.xz
sudo tar xf Python-$VERSION.tar.xz
cd /tmp/Python-$VERSION
sudo ./configure
sudo make
echo "Interactive, high-level language" > description-pak

# This has to be run as root
checkinstall -D \
    --pkgname=$PKGNAME \
    --pkgversion=$VERSION \
    --pkgrelease=$RELEASE \
    --maintainer="aryeh@mokriya.com" \
    --fstrans=no \
    --nodoc \
    --pakdir=/build \
    make install

chown $USERGROUP /build/${PKGNAME}_${VERSION}-${RELEASE}_*.deb
